#157694754 Add failed jobs page
andela/hc-silicon pull request #3
Opened 2018-06-07 12:45 UTC by muhozi

#### What does this PR do?
- Add a tab in the links for the failed jobs(Issues)
- Add a page for the failed jobs
- Add tests for the failed job feature

#### Description of Task to be completed?
A user can click an issue tab/link and view listing of all their failed jobs
#### How should this be manually tested?
- Run the application and click the issues link to view the failed jobs/checks
- Test the added feature by running `./manage.py test hc.front.tests.test_my_checks`
#### What are the relevant pivotal tracker stories?
[#157694754](https://www.pivotaltracker.com/story/show/157694754)

2018-06-07 14:11 UTC, david-kironde-deel requested changes
Kindly add some screen shots for this feature.

2018-06-07 14:11 UTC, Awesome94 commented on static/js/issues.js
> +
why skip two lines here ?

2018-06-08 09:40 UTC, david-kironde-deel approved these changes

2018-06-08 09:40 UTC, david-kironde-deel commented on static/js/issues.js
> +
Looks like too much space in-between.. 🤔

2018-06-08 09:40 UTC, merged

2018-06-08 19:40 UTC, kzyGit commented
Good job Muhozi.